### PR TITLE
Windows linux merge

### PR DESCRIPTION
**Pull request by horttanainen**

### CODE REVIEW

**Comment by horttanainen** [comment]
En tiputtanut committi historiaa, koska täällä näytti kaikki olevan vielä tallella. @mheiskan vastaa tähän, jos haluat tän pullin ilman noita meidän committeja.

**Comment by mheiskan** [comment]
The comments are fine, even though they're in Finnish. No reason to start losing history now.

**Comment by mheiskan** [comment]
A relevant commit to newbase seems to be missing. In Linux gcc gives the following warning:
error: ‘NFmiQueryDataUtil::SignificantSoundingLevels’ has not been declared

**Comment by horttanainen** [comment]
@mheiskan I did a pull request to newbase which should fix these problems.

**Pull request merged**
